Coastal testing v6

diff --git a/.github/workflows/github_actions_CI.yml b/.github/workflows/github_actions_CI.yml
--- a/.github/workflows/github_actions_CI.yml
+++ b/.github/workflows/github_actions_CI.yml
@@ -92,6 +92,21 @@ jobs:
           echo $TST_PUB_DWNL && $TST_PUB_DWNL
           echo $TST_PUB_REPR && $TST_PUB_REPR
           
+      #- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+      #View output
+      #- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+      - name: Show the 36th column of the generated CSV file for debugging
+        run: |
+          echo "Generated CSV 36th column:"
+          cut -d',' -f36 ../output_test/Qout_rivwidth/Qout_pfaf_${{ steps.pfaf }}_rivwidth.csv || echo "Error displaying column"
+
+      - name: Show the 36th column of the expected CSV file for debugging
+        run: |
+          echo "Expected CSV 36th column:"
+          cut -d',' -f36 ../output/Qout_rivwidth/Qout_pfaf_${{ steps.pfaf }}_rivwidth.csv || echo "Error displaying column"
+              
+          
+
 #*******************************************************************************
 #End
 #*******************************************************************************
